version: '3.9'
services:
  web:
    build: .
    ports:
    - "8008:8000"
    environment:
      - YANDEX_API_CLIENT_SECRET
      - SECRET_KEY_TO_MAKE_SOME_JWT
      - MINIGIS_EARTH_ENGINE_KEY_DATA
      - YANDEX_DISK_CLIENT_ID_APP_MINIGIS
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - /home/arthur/dev/pgdata:/var/lib/postgresql/data

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
  pgdata:
