kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minigis-pvc
  labels:
    app: minigis-app
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi