name: CI

on:
    push:
        branches:
            - main

jobs:
    tests_frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Получение репозитория проекта miniGIS на виртуальную машину
              uses: actions/checkout@v3
            
            - name: Установка node
              uses: actions/setup-node@v3

            - name: Установка пакетов npm
              run: cd client && npm ci

            - name: Тестирование Frontend
              run: cd client && npm test