name: CI

on:
    push:
        branches:
            - main

jobs:
    tests_frontend:
      runs-on: ubuntu-latest

      steps:
          - name: Получение репозитория проекта miniGIS на виртуальную машину
            uses: actions/checkout@v3
          
          - name: Установка node
            uses: actions/setup-node@v3

          - name: Установка пакетов npm
            run: cd client && npm ci

          - name: Тестирование Frontend
            run: cd client && npm test
    
    build:
      needs: tests_frontend
      name: Build and push Docker Image
      runs-on: ubuntu-latest

      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub Registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: arthurgo/minigis-web:latest