name: CI

on:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            
            
            - name: Setup node
              uses: actions/setup-node@v3

            - name: npm install
              run: cd client && npm ci

            - name: Test frontend, component <Step0 />
              run: echo pwd && cd client && npm test